
export const ANIMATION_STATE_NORMAL = 'ANIMATION_STATE_NORMAL';
export const ANIMATION_STATE_GROW = 'ANIMATION_STATE_GROW';

export const ANIMATION_STATE_LEFT_START = 'ANIMATION_STATE_LEFT_START';
export const ANIMATION_STATE_LEFT_STEP_ONE = 'ANIMATION_STATE_LEFT_STEP_ONE';
export const ANIMATION_STATE_LEFT_STEP_TWO = 'ANIMATION_STATE_LEFT_STEP_TWO';
export const ANIMATION_STATE_LEFT_STEP_THREE = 'ANIMATION_STATE_LEFT_STEP_THREE';
export const ANIMATION_STATE_LEFT_STEP_FOUR = 'ANIMATION_STATE_LEFT_STEP_FOUR';
export const ANIMATION_STATE_LEFT_STEP_FIVE = 'ANIMATION_STATE_LEFT_STEP_FIVE';
export const ANIMATION_STATE_LEFT_STEP_SIX = 'ANIMATION_STATE_LEFT_STEP_SIX';
export const ANIMATION_STATE_LEFT_STEP_SEVEN = 'ANIMATION_STATE_LEFT_STEP_SEVEN';
export const ANIMATION_STATE_LEFT_STEP_EIGHT = 'ANIMATION_STATE_LEFT_STEP_EIGHT';
export const ANIMATION_STATE_LEFT_STEP_NINE = 'ANIMATION_STATE_LEFT_STEP_NINE';
export const ANIMATION_STATE_LEFT_STEP_TEN = 'ANIMATION_STATE_LEFT_STEP_TEN';
export const ANIMATION_STATE_LEFT_STEP_ELEVEN = 'ANIMATION_STATE_LEFT_STEP_ELEVEN';
export const ANIMATION_STATE_LEFT_STEP_TWELVE = 'ANIMATION_STATE_LEFT_STEP_TWELVE';
export const ANIMATION_TIME_500 = 500;
export const ANIMATION_TIME_250 = 250;
export const ANIMATION_TIME_1000 = 1000;
export const ANIMATION_STATE_RIGHT = 'ANIMATION_STATE_RIGHT';
export const ANIMATION_STATE_LEFT = 'ANIMATION_STATE_LEFT';
